<?php

return [
    '' => 'site/home',
    'admin-post' => 'admin/admin-posts/index',
    'create-admin-post' => 'admin/admin-posts/create',
    'update-admin-post/<id>' => 'admin/admin-posts/update',
    'admin-user' => 'admin/admin-users/index',
    'create-admin-user' => 'admin/admin-users/create',
    'update-admin-user/<id>' => 'admin/admin-users/update',
    'change-password/<id>' => 'admin/admin-users/change-password',
    'step1' => 'steps/step1/index',
    'step2' => 'steps/step2/index',
    'step3' => 'steps/step3/index',
    'step4' => 'steps/step4/index',
    'step5' => 'steps/step5/index',
    'step6' => 'steps/step6/index',
    'step7' => 'steps/step7/index',
    'step8' => 'steps/step8/index',
    'step9' => 'steps/step9/index',
    'step10' => 'steps/step10/index',
    'users' => 'user/users/index',
    'create-user' => 'user/users/create',
    'update-user/<id>' => 'user/users/update',
    'change-password/<id>' => 'user/users/change-password',
    'forgot-password' => 'site/forgot',
    'country-codes' => 'product/country-code/index',
];
